version: "2"
checks:
  method-lines:
    enabled: false

engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"

exclude_paths:
- static/**/*
